FROM python:3.7
RUN pip install flask flask-sqlalchemy pymysql
COPY . . 
EXPOSE 5000
ENTRYPOINT ["python", "app.py"]
#Use Python Image

# Install apt dependencies
 
# Copy contents into image
 
# run pip dependencies
 
# Expose correct port

# Create an entrypoint

